export enum EmailTemplate {
    DEFAULT = 'DEFAULT',
    FORGOT_PASSWORD_OTP_EMAIL = 'FORGOT_PASSWORD_OTP_EMAIL',
    USER_INVITATION = 'USER_INVITATION',
    PENDING_APPROVE = 'PENDING_APPROVE',
    APPROVED_REQUEST = 'APPROVED_REQUEST',
    DONATION_RESULT = 'DONATION_RESULT'
}

export type EmailTemplateType = keyof typeof EmailTemplate;
